import type { Metadata } from "next";

import { TopHeader } from "./components/Top_Header/Top_Header";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { AppProviders } from "./providers/app_providers";
import { BottomFooter } from "./components/Bottom_Footer/BottomFooter";
import { geistSans, geistMono } from "@/fonts/fonts";
import { NextIntlClientProvider } from 'next-intl'
import "./globals.css";
import { Sidebar } from "./components/Sidebar/Sidebar";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import { FallbackErrorBoundary } from "./components/FallbackErrorBoundary/FallbackErrorBoundary";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <NextIntlClientProvider>
        <AppProviders session={session}>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <div className="flex flex-col h-screen">
                <TopHeader />
                <Sidebar />
                {children}
                <BottomFooter />
            </div>
          </body>
        </AppProviders>
      </NextIntlClientProvider>
    </html>
  );
}
